### ISSUE TITLE
Replace for loops by functional approach

### ISSUE THREAD

**Issue by blegat** [jump-dev/MutableArithmetics.jl#26]
Using for loops for generators may create type instabilities, see https://discourse.julialang.org/t/multiplying-by-a-variable-in-a-constraint-causing-type-instability-in-code-warntype/32239 and forces us to create local scopes with `let` in the macro.
We could switch to a functional approach similarly to https://github.com/JuliaOpt/JuMP.jl/pull/2070

Moreover, we currently we rewrite `sum(... for i in ...` but we don't rewrite `sum(i -> ..., ...)`.

**Comment by odow** [comment]
There doesn't seem to be much appetite for this. I haven't seen any issues relating to it since 2019. Can we close?

**Comment by odow** [comment]
The new rewrite #170 adds support for `sum(generator; init)`, but it doesn't add support for the two-argument `sum(f, x)`. I think automatically rewriting that gets a little risky, because we don't know that:
```julia
sum(f, x; init) === sum(f(x) for a in x; init = init)
```
(It might depend on the types, although it'd be pretty poor form to change the semantics of `sum` like that.)

I also don't see how we would use functions instead of the loop, because in the functional case we wouldn't be able to rewrite in-place?

**Comment by odow** [comment]
Closing this as won't-fix. The loops are okay.

**Comment by blegat** [comment]
> I also don't see how we would use functions instead of the loop, because in the functional case we wouldn't be able to rewrite in-place?

I don't see why but the functional approach might allocate because of closure so it might be best to stay with for-loops until closures are faster
