### ISSUE TITLE
missing method for /(::MutableArithmetics.Zero, ::Float64)

### ISSUE THREAD

**Issue by NLaws** [jump-dev/MutableArithmetics.jl#52]
In my model sometimes a decision variable and associated data is not needed so it gets indexed on a `UnitRange` of `1:0` and multiplied by some empty data arrays.  Perhaps there is a more efficient way to handle this case and I'm open to suggestions, but it has brought about the following error:
```julia
julia>  using JuMP

julia>  model = Model();

julia> @variable(model, x[1:0]>=0);

julia> @expression(model, d, sum([] * x[r] for r in 1:0))
MutableArithmetics.Zero()

julia> y = model[:d] / 12.3
ERROR: MethodError: no method matching /(::MutableArithmetics.Zero, ::Float64)
Closest candidates are:
  /(::Float64, ::Float64) at float.jl:407
  /(::Missing, ::Number) at missing.jl:115
  /(::BigFloat, ::Union{Float16, Float32, Float64}) at mpfr.jl:453
  ...
Stacktrace:
 [1] top-level scope at REPL[5]:1
```

**Comment by odow** [comment]
So this is surprisingly non-trivial. I added the methods
```Julia
Base.:/(z::Zero, x::Any) = iszero(x) ? NaN : z
Base.:/(x::Any,  ::Zero) = iszero(x) ? NaN : Inf
Base.:/(z::Zero, ::Zero) = NaN
```
But we get weird things like this:
```julia
julia> MA.@rewrite(sum(1 for i in 1:0) / 0)
MutableArithmetics.Zero()
```
Why? Because it gets rewritten as the equivalent of 
```julia
julia> MA.@rewrite(sum(1 / 0 for i in 1:0))
MutableArithmetics.Zero()
```

There is also the massive issue that---in contrast to `+`, `-`, and `*`---`/` is not a type-stable operation (`1 / 2` is not an `Int`). That means it is inherently non-mutable. One option is to make `MA.Zero` a strong zero, so that anything involving `MA.Zero` and `/` returns a `MA.Zero`. The only case I really see us supporting is dividing `MA.Zero` by a constant like `1.0`, which is okay to return `MA.Zero`. If people divide by 0 on purpose, their code is arguably broken.

**Comment by NLaws** [comment]
@odow I agree with only supporting dividing `MA.Zero` by a constant because as you said if the code is dividing by zero then an exception should be raised anyway.

**Comment by blegat** [comment]
> If people divide by 0 on purpose, their code is arguably broken.

I agree, people would prefer an error if they do `/(::Zero, x)` where `iszero(x)` than having `NaN` returned.
